# Makefile — the local gate for dotfiles-openSUSE.
# ──────────────────────────────────────────────────────────────────────────────
# Before this existed there was no way to validate the repo short of running
# ./bootstrap.sh for real against your own machine, and core.lock's own header told
# you to run `make core-lock` — a target that did not exist here (Core's
# RELEASE-STRATEGY.md already notes most consumers have no root Makefile). These
# targets mirror what CI actually runs, so local == CI.
#
# Scope note: this repo owns bootstrap.sh, os/, install/, ssh/, wsl/ and .github/.
# core/ is vendored and is NEVER linted or edited here — it is gated upstream in
# dotfiles-core by `make audit`, and guarded here by `make check-core`.

# A real executable path: make execs SHELL directly and does NOT word-split it, so
# `/usr/bin/env bash` would be looked up as a single filename and fail. openSUSE always
# ships /bin/bash.
SHELL       := /bin/bash
CORE_REMOTE ?= https://github.com/dotgibson/dotfiles-core.git

# Repo-owned shell only; core/ is excluded everywhere on purpose.
SH_FILES    := bootstrap.sh
ZSH_FILES   := $(wildcard os/*.zsh)

.DEFAULT_GOAL := help
.PHONY: help lint lint-sh lint-zsh lint-actions check-core core-lock bootstrap-dry test

help: ## Show this help
	@echo "dotfiles-openSUSE — local targets:"
	@grep -hE '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk -F':.*?## ' '{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'
	@echo
	@echo "  Pre-push gate: make test"

lint: lint-sh lint-zsh lint-actions ## Run every linter (shellcheck + zsh -n + actionlint)

lint-sh: ## ShellCheck the repo-owned bash (uses ./.shellcheckrc)
	@if command -v shellcheck >/dev/null 2>&1; then \
	  echo ":: shellcheck $(SH_FILES)"; \
	  shellcheck -x $(SH_FILES); \
	  echo "   ok"; \
	else \
	  echo "!! shellcheck not installed — skipping (zypper in ShellCheck)"; \
	fi
	@echo ":: bash -n $(SH_FILES)"; bash -n $(SH_FILES) && echo "   ok"

lint-zsh: ## Parse-check the zsh OS layer (ShellCheck has no zsh mode)
	@if command -v zsh >/dev/null 2>&1; then \
	  for f in $(ZSH_FILES); do echo ":: zsh -n $$f"; zsh -n "$$f" || exit 1; done; \
	  echo "   ok"; \
	else \
	  echo "!! zsh not installed — skipping"; \
	fi

lint-actions: ## actionlint the workflow callers
	@if command -v actionlint >/dev/null 2>&1; then \
	  echo ":: actionlint .github/workflows"; actionlint && echo "   ok"; \
	else \
	  echo "!! actionlint not installed — skipping (CI still enforces it)"; \
	fi

check-core: ## Verify vendored core/ matches the commit core.lock pins (mirrors CI's guard / integrity)
	@set -euo pipefail; \
	test -r core.lock || { echo "!! core.lock missing"; exit 1; }; \
	ver="$$(sed -n 's/^core_version=//p' core.lock)"; \
	sha="$$(sed -n 's/^core_sha=//p' core.lock)"; \
	test -n "$$sha" || { echo "!! core.lock records no core_sha"; exit 1; }; \
	echo ":: core.lock pins $$ver ($${sha:0:12})"; \
	vfile="$$(cat core/core.version 2>/dev/null || echo '')"; \
	if [ "$$vfile" != "$$ver" ]; then \
	  echo "!! core/core.version ($$vfile) != core.lock core_version ($$ver) — botched sync"; exit 1; \
	fi; \
	echo "   core/core.version agrees"; \
	if ! git diff --quiet HEAD -- core/; then \
	  echo "!! core/ has uncommitted local modifications — it is vendored and must not be hand-edited"; \
	  git diff --stat HEAD -- core/; exit 1; \
	fi; \
	echo "   core/ has no local edits"; \
	vend="$$(git rev-parse 'HEAD:core')"; \
	if ! git rev-parse --verify --quiet "$$sha^{tree}" >/dev/null; then \
	  echo ":: fetching pinned commit from $(CORE_REMOTE) (treeless)"; \
	  git fetch --quiet --depth=1 --filter=tree:0 "$(CORE_REMOTE)" "$$sha" || { \
	    echo "!! could not fetch $$sha — offline? local checks above still passed"; exit 1; }; \
	fi; \
	exp="$$(git rev-parse --verify "$$sha^{tree}")"; \
	if [ "$$vend" = "$$exp" ]; then \
	  echo "   tree matches upstream: $$vend"; echo ":: core integrity OK"; \
	else \
	  echo "!! MISMATCH  vendored=$$vend  expected=$$exp"; \
	  echo "   Fix upstream in dotfiles-core, then 'make sync' there. Never hand-edit core/."; \
	  exit 1; \
	fi

core-lock: ## Regenerate core.lock after a manual 'git subtree pull'
	@set -euo pipefail; \
	ver="$$(cat core/core.version)"; \
	test -n "$$ver" || { echo "!! core/core.version is empty"; exit 1; }; \
	echo ":: resolving v$$ver in $(CORE_REMOTE)"; \
	sha="$$(git ls-remote "$(CORE_REMOTE)" "refs/tags/v$$ver^{}" | cut -f1)"; \
	test -n "$$sha" || { echo "!! no tag v$$ver upstream — is core/core.version right?"; exit 1; }; \
	{ echo "# GENERATED by dotfiles-openSUSE 'make core-lock' — vendored Core provenance (B1)."; \
	  echo "# Regenerate after a manual 'git subtree pull' with: make core-lock"; \
	  echo "core_version=$$ver"; \
	  echo "core_sha=$$sha"; \
	  echo "core_branch=$$sha"; \
	  echo "core_tag=v$$ver"; } > core.lock; \
	echo ":: core.lock -> v$$ver ($${sha:0:12})"; \
	$(MAKE) --no-print-directory check-core

bootstrap-dry: ## Preview every symlink bootstrap would create; mutates nothing
	./bootstrap.sh --links-only --dry-run

test: lint check-core ## The pre-push gate: lint + core integrity
	@echo
	@echo ":: all local checks passed"
